# Generated by Django 2.0.13 on 2019-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('type', models.CharField(choices=[('b', 'Book'), ('eb', 'eBook'), ('d', 'DVD Movie'), ('c', 'CD Music'), ('a', 'Audio Book')], default=True, max_length=5)),
                ('year', models.IntegerField(default=True, verbose_name=2019)),
                ('picture', models.TextField()),
            ],
            options={
                'db_table': 'Books',
            },
        ),
    ]
