# Generated by Django 2.0.13 on 2019-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.IntegerField(default=True, max_length=2019),
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
