# Generated by Django 2.0.13 on 2019-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190828_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('mf', 'Mystery Fiction'), ('dm', 'Detective and Mystery Stories'), ('sf', 'Suspense Fiction'), ('hf', 'Historical Fiction'), ('af', 'Adventure Fiction'), ('ff', 'Fantasy Fiction'), ('cf', 'Christian Fiction'), ('jf', 'Juvenile Fiction'), ('pf', 'Psycological Fiction'), ('hf', 'Horror Fiction'), ('jsr', 'Juvenile Sound Recordings')], default=True, max_length=5),
        ),
    ]
