# Generated by Django 2.0.13 on 2019-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190829_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Mystery Fiction', 'Mystery Fiction'), ('Detective and Mystery Stories', 'Detective and Mystery Stories'), ('Suspense Fiction', 'Suspense Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Adventure Fiction', 'Adventure Fiction'), ('Fantasy Fiction', 'Fantasy Fiction'), ('Christian Fiction', 'Christian Fiction'), ('Juvenile Fiction', 'Juvenile Fiction'), ('Psycological Fiction', 'Psycological Fiction'), ('Horror Fiction', 'Horror Fiction'), ('Juvenile Sound Recordings', 'Juvenile Sound Recordings')], default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='type',
            field=models.CharField(choices=[('Book', 'Book'), ('eBook', 'eBook'), ('DVD Movie', 'DVD Movie'), ('CD Music', 'CD Music'), ('Audio Book', 'Audio Book')], default=True, max_length=20),
        ),
    ]
