# Generated by Django 2.0.13 on 2019-08-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190830_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Checked Out', 'Checked Out'), ('Returned', 'Returned'), ('Place a Hold', 'Place a Hold')], default=True, max_length=20)),
            ],
        ),
    ]
