# Generated by Django 2.0.13 on 2019-08-30 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bookactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='entered_lib',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
