# Generated by Django 2.0.13 on 2019-09-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190830_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookactivity',
            name='book',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookactivity',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookactivity',
            name='activity',
            field=models.CharField(choices=[('Checked Out', 'Checked Out'), ('Returned', 'Returned')], default=True, max_length=20),
        ),
    ]
