# Generated by Django 2.0.13 on 2019-09-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190918_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookactivitie',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='bookactivitie',
            name='book',
        ),
    ]
