# Generated by Django 2.0.13 on 2019-09-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bookactivitie_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookactivitie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book'),
        ),
    ]
