# Generated by Django 2.0.13 on 2019-09-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190929_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookactivitie',
            name='user',
        ),
    ]
