# Generated by Django 2.0.13 on 2019-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_bookactivitie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookactivitie',
            name='book',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookactivitie',
            name='user',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
