# Generated by Django 2.1.15 on 2023-12-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bookactivitie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=True),
        ),
    ]
